version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile  # Nome do Dockerfile do MariaDB
    container_name: mariadb_container
    ports:
      - "3306:3306"
    networks:
      - pi_network
    environment:
      MARIADB_ROOT_PASSWORD: p@55w.rd
      MARIADB_DATABASE: db_PI
      MARIADB_USER: pIuser
      MARIADB_PASSWORD: pI123
networks:
  pi_network:
    driver: bridge
