POST http://localhost:5000/inserir_ponto
Content-Type: application/json
Cookie: auth_token=ImpvYW8i.aBgZrA.YFquojE5-vDBiF0UjMEnYhUdSmQ

{
  "timestamp": "2025-05-04 23:45:00",
  "Authenticator":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiam9hbyIsImNwZiI6IjEyMzQ1Njc4OTAxIiwiY2FyZ28iOiJ0aSIsImV4cCI6MTc0NzE5MjM2MX0.0n3oHvgXus_oRLmeyzEzZk2VzRPy2x_VE4tt5FFR9jQ"
}